version: '3.8'

services:
  pgdb:
    
    container_name: pgdb_node
    
    image: postgres
    
    restart: always
    
    ports:
      - 5432:5432
    
    logging:
      options:
        max-size: 10m
        max-file: "3"
    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres